### ISSUE TITLE
new epochserver.so (0.5.1.8) crashes server

### ISSUE THREAD

**Issue by SirDice** [EpochModTeam/Epoch#644]
Just updated my Epoch Experimental server, it was running fine up to b628. Build 629 and onward requires updating epochserver.so. Initialization seems to work fine but when the game actually starts it coredumps arma3. 

Last bit of logging (I have more if needed):
```22:10:53 "CfgEpochCoreServerFunctions"
22:10:53 [4378,38.639,0,"XEH: PreInit started. v3.1.1.161012"]
22:10:54 [XEH]: One or more children of class Air do not support Extended Event Handlers. Fall back to loop.
22:10:54 [4378,39.051,0,"XEH: PreInit finished."]
22:10:54 "Loading Functions: CfgServerFunctions"
22:10:54 Mission read.
22:10:54 Connected to Steam servers
22:10:54 [4378,39.239,0,"XEH: PostInit started. MISSIONINIT: missionName=epoch, missionVersion=52, worldName=Takistan, isMultiplayer=true, isServer=true, isDedicated=true, CBA_isHeadlessClient=false, hasInterface=false, didJIP=false"]
22:10:54 [4378,39.27,0,"CBA_VERSIONING: cba=3.1.1.161012, "]
22:10:54 [4378,39.279,0,"XEH: PostInit finished."]
22:10:54 ../lib/Network/networkServer.cpp OnClientStateChanged:NOT IMPLEMENTED - briefing!
22:10:54  Mission id: 4505ed8e01a65cf4365bb810f00fc71c19ed7bd0
22:10:54 Game started.
22:10:54 "Epoch: Starting ArmA3 Epoch Server, Version 0.4.0.0"
WATCHDOG (1363): [Mon Oct 31 22:10:56 CET 2016] Server died, waiting to restart...
WATCHDOG (1363): [Mon Oct 31 22:11:01 CET 2016] Starting server (port 2302)...
22:11:01 Could not enable linux core dumps. Error 1 -
22:11:01 SteamAPI initialization failed. Steam features wont's be accessible!
22:11:01 Initializing stats manager.
22:11:01 Stats config disabled.
<it continues starting up again, then crashes at the same point>
```
I have a Linux dedicated server (appid 233780) running on an up to date Debian 8.6.

**Comment by vbawol** [comment]
can you run this check and report back if you had anything missing 
ldd epochserver.so

```
ldd epochserver.so
        linux-gate.so.1 =>  (0xb7730000)
        libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xb755f000)
        libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb7539000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb751b000)
        libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb73cc000)
        /lib/ld-linux.so.2 (0xb7731000)

```

If you have any other logs or errors please do provide them.

**Comment by SirDice** [comment]
That seems to be in order:

```
steam@riviera:~/arma3ds/@epochhive$ ldd epochserver.so
        linux-gate.so.1 (0xf779e000)
        libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf75c3000)
        libm.so.6 => /lib/i386-linux-gnu/i686/cmov/libm.so.6 (0xf757d000)
        libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf755f000)
        libc.so.6 => /lib/i386-linux-gnu/i686/cmov/libc.so.6 (0xf73b2000)
        /lib/ld-linux.so.2 (0xf77a1000)
```

/var/log/messages show me this:

```
Oct 31 22:09:14 riviera kernel: [  243.318344] arma3server[1251]: segfault at 80706 ip 0000000000080706 sp 00000000ffac9b0c error 14 in arma3server[8048000+22e6000]
Oct 31 22:10:54 riviera kernel: [  343.859194] arma3server[1375]: segfault at 80706 ip 0000000000080706 sp 00000000ffb7113c error 14 in arma3server[8048000+22e6000]
Oct 31 22:11:41 riviera kernel: [  390.215945] arma3server[1415]: segfault at 80706 ip 0000000000080706 sp 00000000ffa9372c error 14 in arma3server[8048000+22e6000]
Oct 31 22:14:09 riviera kernel: [  538.116401] arma3server[1531]: segfault at 80706 ip 0000000000080706 sp 00000000ff83843c error 14 in arma3server[8048000+22e6000]
Nov  1 00:13:07 riviera kernel: [ 7676.262748] arma3server[2275]: segfault at 80706 ip 0000000000080706 sp 00000000ffae79cc error 14 in arma3server[8048000+22e6000]
Nov  1 00:13:56 riviera kernel: [ 7725.055124] arma3server[2315]: segfault at 80706 ip 0000000000080706 sp 00000000ff9004ec error 14 in arma3server[8048000+22e6000]
Nov  1 00:14:43 riviera kernel: [ 7772.709179] arma3server[2362]: segfault at 80706 ip 0000000000080706 sp 00000000ffac8e8c error 14 in arma3server[8048000+22e6000]
```

I'll enable core dumps and see if that provides more clues.

**Comment by SirDice** [comment]
It doesn't tell me anything more but maybe it'll help

```
steam@riviera:~/arma3ds$ gdb arma3server core-arma3server-11-1001-1001-1753-1477958196
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from arma3server...(no debugging symbols found)...done.
BFD: Warning: /home/steam/arma3ds/core-arma3server-11-1001-1001-1753-1477958196 is truncated: expected core file size >= 1639047168,
 found: 1024000000.
[New LWP 1753]
[New LWP 1754]
[New LWP 1768]
[New LWP 1774]
[New LWP 1775]
[New LWP 1776]
[New LWP 1782]
[New LWP 1777]
[New LWP 1784]
[New LWP 1783]
[New LWP 1778]
Cannot access memory at address 0xf770691c
Cannot access memory at address 0xf7706918
(gdb) bt
#0  0x00080706 in ?? ()
Cannot access memory at address 0xffd003dc
(gdb) i s
#0  0x00080706 in ?? ()
Cannot access memory at address 0xffd003dc
(gdb) i r
eax            0xffd0041a       -3144678
ecx            0xa33f10c        171176204
edx            0xffd009d0       -3143216
ebx            0xad0f9c64       -1391485852
esp            0xffd003dc       0xffd003dc
ebp            0xffd00908       0xffd00908
esi            0x7c     124
edi            0xffd009bc       -3143236
eip            0x80706  0x80706
eflags         0x210282 [ SF IF RF ID ]
cs             0x23     35
ss             0x2b     43
ds             0x2b     43
es             0x2b     43
fs             0x0      0
gs             0x63     99
(gdb) quit
```

**Comment by vbawol** [comment]
Thanks for testing! I am having issues with my new Arma 3 Linux dev test server segfaulting on a fresh install without any mods, so I am still unable to test this atm.

However, I did rebuild the epochserver.so to statically link to libpcre.a and libpcrecpp.a and not just libpcrecpp.a, and I think that should fix it, can you please give this one a test:
https://github.com/EpochModTeam/Epoch/raw/ae18103ddc1c92d5e498d14f3aea7f1f0a2f0bc1/Server_Install_Pack/%40epochhive/epochserver.so

**Comment by SirDice** [comment]
Thanks for looking into it. This one seems to work, server starts normally now and I can login again.

```
 8:25:26 "Epoch: Server Start Complete: 5.664 seconds"
```

I'm getting a bunch of BE script kicks but that's a different issue. I'll look into those when I get home from work.

**Comment by vbawol** [comment]
Sweet, make sure you have updated your BE filters, as I have fixed a few typos and some missing filters. https://github.com/EpochModTeam/Epoch/tree/experimental/Server_Install_Pack/sc/BattlEye
